version: '3.8'

services:
  # Servicio para la base de datos (MySQL)
  database:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - app_network

  # Servicio para Symfony (tu aplicación)
  app:
    build:
      context: .
    container_name: symfony_app
    networks:
      - app_network
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: mysql://root:root@database:3306/proyecto
    command: ["php-fpm"]

  # Servicio para Nginx
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    networks:
      - app_network
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html

# Definimos la red común entre todos los servicios
networks:
  app_network:
    driver: bridge

# Volumen para la base de datos
volumes:
  database_data: