version: '3.8'

services:
  # Servicio para Symfony
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    image: symfony-api
    container_name: symfony_api
    ports:
      - "80:80"   # Mapea el puerto 80 del contenedor al puerto 80 de tu máquina
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/proyecto
    depends_on:
      - db
    networks:
      - symfony_network
    volumes:
      - .:/var/www/html

  # Servicio para MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - symfony_network
    volumes:
      - db_data:/var/lib/mysql

# Definir la red personalizada
networks:
  symfony_network:
    driver: bridge

# Definir el volumen para los datos de la base de datos
volumes:
  db_data: