version: '3.8'

services:
  symfony:
    image: your-dockerhub-username/your-symfony-app:latest  # Aquí puedes poner la imagen que construyas o el nombre de la imagen Docker que quieras usar
    container_name: symfony-app
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://symfony:password@db:3306/symfony_db
      - MAILER_DSN=smtp://localhost:25  # Ajusta según el servicio de correo que utilices
    ports:
      - "80:80"  # Puerto expuesto para acceder a la aplicación
    volumes:
      - ./public:/var/www/html/public  # Mapea los archivos locales (como public/) al contenedor
      - ./var:/var/www/html/var  # Mapea el directorio 'var' para almacenar caché y logs
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7  # Imagen de MySQL (puedes cambiarla por otro sistema de base de datos como PostgreSQL)
    container_name: symfony-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql  # Persistir los datos de la base de datos
    networks:
      - app-network

  # Puedes agregar más servicios como un servidor de correo, Redis, o cualquier otro servicio que necesite tu aplicación

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
