name: Deploy Symfony API to AWS EC2

on:
  push:
    branches:
      - alberto

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construirla y etiquetar la imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/symfony-api:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/symfony-api:latest ${{ secrets.DOCKER_USERNAME }}/symfony-api:${{ github.sha }}

      - name: Subir la imagen a Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/symfony-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/symfony-api:${{ github.sha }}

      - name: Configurar SSH y desplegar en EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ubuntu
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/symfony-api:latest
            docker stop symfony_api || true
            docker rm symfony_api || true
            docker run -d --name symfony_api -p 80:80 ${{ secrets.DOCKER_USERNAME }}/symfony-api:latest
